/**
 * Public surface of `@lametrader/core` — the shared types package.
 *
 * Holds the platform's type declarations (interfaces, type aliases,
 * discriminated unions), enums, and the handful of runtime values shared with
 * the browser (`periodMillis`, the input-limit constants). All domain logic and
 * error classes live in `@lametrader/server`; nothing here performs I/O or
 * imports outward.
 */

export type {
  BackfillRange,
  BaseCandle,
  Candle,
  CandleBatch,
  CandlePage,
  CandleRepository,
  CryptoCandle,
  EquityCandle,
  FxCandle,
} from './candle.types.js';
export { type Config, ConfigKey, type ConfigRepository, Period } from './config.types.js';
export type { Expiration } from './expiration.types.js';
export {
  type EnumFieldDescriptor,
  type EnumOption,
  type EnumStateFieldDescriptor,
  type FieldDescriptor,
  FieldType,
  type IndicatorComputeResult,
  type IndicatorDefinition,
  type IndicatorModule,
  type IndicatorStateEvent,
  type IndicatorStateListener,
  type IndicatorStatePoint,
  type InferFieldValue,
  type InferInputs,
  type InferStateRow,
  type InferStateSeries,
  type InferStateValue,
  type NumberFieldDescriptor,
  type NumberStateFieldDescriptor,
  Pane,
  PriceSource,
  RenderKind,
  type SourceFieldDescriptor,
  type StateFieldDescriptor,
} from './indicator.types.js';
export {
  BOT_TOKEN_MAX,
  CHAT_ID_MAX,
  DESTINATION_NAME_MAX,
  RULE_DESCRIPTION_MAX,
  RULE_NAME_MAX,
  STATE_KEY_MAX,
  SYMBOL_ID_MAX,
  TELEGRAM_TEMPLATE_MAX,
} from './limits.js';
export type { Notifier } from './notifier.types.js';
export { periodMillis } from './period.js';
export {
  type AllScope,
  type IndicatorInstance,
  type Profile,
  type ProfileFields,
  type ProfileRepository,
  ProfileScope,
  type ProfileScopeSpec,
  type SymbolsScope,
} from './profile.types.js';
export type {
  EnrichedSymbol,
  SymbolQuote,
  SymbolQuoteEvent,
  SymbolQuoteListener,
} from './quote.types.js';
export {
  type Action,
  ActionKind,
  type AllSymbolsRuleScope,
  type BarClosedEvent,
  type BarOpenedEvent,
  type ChannelLeafCondition,
  ChannelOperator,
  type CloseChangedEvent,
  type ComparisonLeafCondition,
  ComparisonOperator,
  type ConditionNode,
  ConditionNodeKind,
  type ConditionOperand,
  type CrossingLeafCondition,
  CrossingOperator,
  type CycleOverflowRuleEvent,
  type DataUpdateEvent,
  DataUpdateKind,
  type ErrorRuleEvent,
  type EvaluationTriggerEvent,
  EvaluationTriggerKind,
  type EventLog,
  type EventLogAppendListener,
  type EventLogAppendTarget,
  type EveryTimeTrigger,
  type FiredRuleEvent,
  type GlobalStateChangedEvent,
  type HighChangedEvent,
  type IndicatorChangedEvent,
  type LeafCondition,
  LeafConditionFamily,
  type LowChangedEvent,
  type MovingLeafCondition,
  MovingOperator,
  type NotificationAction,
  NotificationChannel,
  type NotificationSentRuleEvent,
  type OncePerBarCloseTrigger,
  type OncePerBarOpenTrigger,
  type OncePerBarTrigger,
  type OncePerIntervalTrigger,
  type OnceTrigger,
  type OpenChangedEvent,
  OperandKind,
  type Operator,
  type RemoveGlobalStateAction,
  type RemoveSymbolStateAction,
  type Rule,
  type RuleEvent,
  type RuleEventContext,
  type RuleEventEntry,
  type RuleEventLookupSnapshot,
  RuleEventType,
  type RuleRepository,
  type RuleScope,
  RuleScopeKind,
  type SetGlobalStateAction,
  type SetSymbolStateAction,
  type StateLeafCondition,
  StateOperator,
  type StateRemovedRuleEvent,
  type StateSetRuleEvent,
  type SymbolRuleScope,
  type SymbolStateChangedEvent,
  type SymbolsRuleScope,
  type TickEvent,
  type TimerEvent,
  type Trigger,
  TriggerKind,
  type VolumeChangedEvent,
} from './rules/index.js';
export { type StateValue, StateValueType } from './state.types.js';
export {
  type GlobalStateScope,
  type StateChangedEvent,
  type StateChangedListener,
  type StateRepository,
  StateScope,
  type StateScopeSpec,
  type SymbolStateScope,
} from './state-repository.types.js';
export {
  type CandleFeed,
  type Instrument,
  type MarketDataSource,
  type SymbolDiscovery,
  SymbolType,
  type WatchedSymbol,
  type WatchlistRepository,
} from './symbol.types.js';
export type {
  TelegramDestination,
  TelegramDestinationLookup,
  TelegramDestinationSummary,
} from './telegram-destination.types.js';
